### PR TITLE
Tooltip hover effect 

### PR DESCRIPTION
**Pull request by ifeday1**

### CODE REVIEW

**Comment by Joshuajee** [comment]
Again where my Ticket?

**Comment by ifeday1** [comment]
I don't understand

**Comment by Joshuajee** [comment]
Linear ticket

**Comment by Joshuajee** [comment]
conflict yarn.lock

**Comment by ifeday1** [comment]
Resolved

**Comment by ifeday1** [comment]
https://linear.app/hng-team-clutch/issue/FRO-93/icons-should-be-described-when-hovered-on-and-its-state-should-change

**Comment by Joshuajee** [comment]
Your linear ticket?

**Comment by ifeday1** [comment]
Sent

**Review by Joshuajee — APPROVED** [review]

**Pull request merged**
