### PR TITLE
Done

### PR DESCRIPTION
**Pull request by ifeday1**

### CODE REVIEW

**Comment by Joshuajee** [comment]
What is done?

**Comment by ifeday1** [comment]
Term of use

**Comment by Joshuajee** [comment]
Linear Ticket url?

**Comment by ifeday1** [comment]
https://linear.app/hng-team-clutch/issue/FRO-97/merge-terms-of-service-and-terms-and-condition-page-as-one

**Review by Joshuajee — APPROVED** [review]

**Pull request merged**
